# Generated by Django 6.1 on 2026-09-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('keywords', models.CharField(help_text='Comma separated keywords, e.g: appointment,book,schedule', max_length=255)),
                ('answer', models.TextField()),
            ],
            options={
                'ordering': ['question'],
            },
        ),
    ]
