# Generated by Django 6.1 on 2026-08-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('ORTHOPEDICS', 'Orthopedics'), ('NEUROLOGY', 'Neurology'), ('CARDIOLOGY', 'Cardiology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('GENERAL_MEDICINE', 'General Medicine'), ('PEDIATRICS', 'Pediatrics'), ('PULMONOLOGY', 'Pulmonology')], max_length=30, null=True),
        ),
    ]
