# Generated by Django 6.1 on 2026-08-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='activation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
